<?php
declare(strict_types=1);

/** Singleton PDO wrapper. Reads config/database.php (regenerated by the installer). */
class Database
{
    private static ?Database $instance = null;
    private PDO $connection;

    private function __construct()
    {
        $config = require CONFIG_PATH . '/database.php';
        $dsn = sprintf(
            '%s:host=%s;port=%d;dbname=%s;charset=%s',
            $config['driver'],
            $config['host'],
            $config['port'],
            $config['database'],
            $config['charset']
        );
        $this->connection = new PDO($dsn, $config['username'], $config['password'], [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
            PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true,
        ]);
    }

    public static function getInstance(): self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * True only when config/database.php exists with credentials that can actually
     * connect. Used at boot to detect a "new environment": a lock file copied from
     * another machine (or rotated credentials) must not make the app believe it is
     * installed and then crash with a raw PDOException on the first page load.
     */
    public static function isReachable(): bool
    {
        $configFile = CONFIG_PATH . '/database.php';
        if (!is_file($configFile)) {
            return false;
        }
        try {
            $config = require $configFile;
            if (empty($config['host']) || empty($config['database']) || empty($config['username'])) {
                return false;
            }
            $dsn = sprintf(
                '%s:host=%s;port=%d;dbname=%s;charset=%s',
                $config['driver'] ?? 'mysql',
                $config['host'],
                $config['port'] ?? 3306,
                $config['database'],
                $config['charset'] ?? 'utf8mb4'
            );
            $pdo = new PDO($dsn, $config['username'], $config['password'] ?? '', [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_TIMEOUT => 3,
            ]);
            $pdo->query('SELECT 1');
            return true;
        } catch (Throwable) {
            return false;
        }
    }

    public function getConnection(): PDO
    {
        return $this->connection;
    }

    /**
     * Runs idempotent in-place migrations for already-installed databases
     * (the installer only applies schema.sql once, so later feature columns
     * must be added here). Each migration runs at most once and the result is
     * stamped to storage/migrations.json. Failures are logged, never fatal.
     */
    public static function migrate(): void
    {
        try {
            $stampFile = STORAGE_PATH . '/migrations.json';
            $done = [];
            if (is_file($stampFile)) {
                $decoded = json_decode((string) file_get_contents($stampFile), true);
                $done = is_array($decoded) ? $decoded : [];
            }
            $pdo = self::getInstance()->getConnection();
            foreach (self::migrations() as $name => $fn) {
                if (in_array($name, $done, true)) {
                    continue;
                }
                $fn($pdo);
                $done[] = $name;
                @file_put_contents($stampFile, json_encode($done));
            }
        } catch (Throwable $e) {
            error_log('Database::migrate skipped: ' . $e->getMessage());
        }
    }

    private static function migrations(): array
    {
        return [
            '2026_01_media_source' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'media_post_items', 'source', "ENUM('upload','youtube') NOT NULL DEFAULT 'upload'", 'type');
            },
            '2026_01_media_saves' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'media_posts', 'saves_count', 'INT NOT NULL DEFAULT 0', 'views_count');
            },
            '2026_01_media_engagement' => function (PDO $pdo): void {
                $pdo->exec("CREATE TABLE IF NOT EXISTS `post_saves` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `media_post_id` INT NOT NULL,
                    `fingerprint_hash` VARCHAR(64) NOT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_save_post_fingerprint` (`media_post_id`, `fingerprint_hash`),
                    FOREIGN KEY (`media_post_id`) REFERENCES `media_posts`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                $pdo->exec("CREATE TABLE IF NOT EXISTS `post_comments` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `media_post_id` INT NOT NULL,
                    `name` VARCHAR(100) NULL,
                    `message` TEXT NOT NULL,
                    `fingerprint_hash` VARCHAR(64) NULL,
                    `is_published` TINYINT(1) NOT NULL DEFAULT 1,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`media_post_id`) REFERENCES `media_posts`(`id`) ON DELETE CASCADE,
                    INDEX `idx_comment_post` (`media_post_id`, `created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_08_media_converted_at' => function (PDO $pdo): void {
                // Set when an uploaded video finishes its 9:16 crop. NULL means it
                // still plays the original (conversion pending or ffmpeg absent).
                self::addColumnIfMissing($pdo, 'media_post_items', 'converted_at', 'DATETIME NULL', 'processing_status');
            },
            '2026_08_forms' => function (PDO $pdo): void {
                $pdo->exec("CREATE TABLE IF NOT EXISTS `forms` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `title` VARCHAR(200) NOT NULL,
                    `slug` VARCHAR(220) NOT NULL UNIQUE,
                    `description` TEXT NULL,
                    `submit_label` VARCHAR(100) NOT NULL DEFAULT 'Submit',
                    `end_at` DATETIME NULL COMMENT 'Optional validity end date; NULL = open-ended',
                    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    INDEX `idx_active_end` (`is_active`, `end_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                $pdo->exec("CREATE TABLE IF NOT EXISTS `form_fields` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `form_id` INT NOT NULL,
                    `label` VARCHAR(255) NOT NULL,
                    `field_type` ENUM('text','textarea','email','phone','number','date','url','select','radio','checkbox') NOT NULL DEFAULT 'text',
                    `placeholder` VARCHAR(255) NULL,
                    `options` TEXT NULL COMMENT 'One option per line (select/radio/checkbox)',
                    `required` TINYINT(1) NOT NULL DEFAULT 0,
                    `sort_order` INT NOT NULL DEFAULT 0,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`form_id`) REFERENCES `forms`(`id`) ON DELETE CASCADE,
                    INDEX `idx_field_form_order` (`form_id`, `sort_order`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                $pdo->exec("CREATE TABLE IF NOT EXISTS `form_submissions` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `form_id` INT NOT NULL,
                    `data` LONGTEXT NOT NULL COMMENT 'JSON map of field id -> value',
                    `ip_address` VARCHAR(45) NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`form_id`) REFERENCES `forms`(`id`) ON DELETE CASCADE,
                    INDEX `idx_submission_form_time` (`form_id`, `created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_08_forms_image_field' => function (PDO $pdo): void {
                // Widens form_fields.field_type to accept the new 'image' upload type.
                $pdo->exec("ALTER TABLE `form_fields` MODIFY COLUMN `field_type` ENUM('text','textarea','email','phone','number','date','url','select','radio','checkbox','image') NOT NULL DEFAULT 'text'");
            },
            '2026_08_pages' => function (PDO $pdo): void {
                // Homepage hero: editable eyebrow text, background image, and CTA labels/links.
                self::addColumnIfMissing($pdo, 'settings', 'hero_eyebrow', "VARCHAR(120) NULL", 'hero_scripture');
                self::addColumnIfMissing($pdo, 'settings', 'hero_image_path', "VARCHAR(255) NULL", 'hero_eyebrow');
                self::addColumnIfMissing($pdo, 'settings', 'hero_cta_primary_label', "VARCHAR(60) NULL", 'hero_image_path');
                self::addColumnIfMissing($pdo, 'settings', 'hero_cta_primary_url', "VARCHAR(500) NULL", 'hero_cta_primary_label');
                self::addColumnIfMissing($pdo, 'settings', 'hero_cta_secondary_label', "VARCHAR(60) NULL", 'hero_cta_primary_url');
                self::addColumnIfMissing($pdo, 'settings', 'hero_cta_secondary_url', "VARCHAR(500) NULL", 'hero_cta_secondary_label');

                // CMS pages table (JSON section-based content rendered into a template).
                $pdo->exec("CREATE TABLE IF NOT EXISTS `pages` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `title` VARCHAR(200) NOT NULL,
                    `slug` VARCHAR(220) NOT NULL UNIQUE,
                    `eyebrow` VARCHAR(120) NULL,
                    `content` LONGTEXT NULL COMMENT 'JSON array of content sections',
                    `meta_description` VARCHAR(255) NULL,
                    `in_nav` TINYINT(1) NOT NULL DEFAULT 0,
                    `nav_label` VARCHAR(60) NULL,
                    `is_published` TINYINT(1) NOT NULL DEFAULT 1,
                    `sort_order` INT NOT NULL DEFAULT 0,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    INDEX `idx_page_nav` (`is_published`, `in_nav`, `sort_order`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                // Seed the About page so the existing /about link has CMS content.
                $check = $pdo->prepare('SELECT COUNT(*) FROM pages WHERE slug = ?');
                $check->execute(['about']);
                if (!(int) $check->fetchColumn()) {
                    $content = json_encode([
                        ['type' => 'text', 'heading' => 'Welcome to Grace & Life Church', 'body' => 'We are a family of believers on a journey together — growing in faith, building community, and serving our city with the love of Christ.', 'align' => 'center'],
                        ['type' => 'columns', 'heading' => 'Why We Exist', 'columns' => [
                            ['heading' => 'Our Mission', 'body' => 'To lead people into a growing relationship with God, build authentic community, and serve our city with the love of Christ.'],
                            ['heading' => 'Our Vision', 'body' => 'A church without walls — reaching every generation, in the room and online, with hope that lasts.'],
                            ['heading' => 'Our Values', 'body' => 'Grace first. People over programs. Faith in action. Generosity, humility, and love in everything we do.'],
                        ]],
                        ['type' => 'quote', 'quote' => 'Wherever you are on your journey, you are welcome here — exactly as you are.', 'source' => 'Grace & Life Church'],
                        ['type' => 'cta', 'title' => 'Come worship with us this weekend', 'subtitle' => 'Every Sunday — in the room and online.', 'label' => 'Plan a Visit', 'url' => '/contact'],
                    ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
                    $pdo->prepare('INSERT INTO pages (title, slug, eyebrow, content, meta_description, in_nav, nav_label, sort_order) VALUES (?, ?, ?, ?, ?, 1, ?, 10)')
                        ->execute(['About Us', 'about', 'Our Story', $content, 'Learn about our story, mission, vision, and values.', 'About']);
                }
            },
            '2026_08_service_times_seed' => function (PDO $pdo): void {
                // Store the default service schedule in the settings row so the
                // DB is the single source of truth for every display spot (home,
                // footer, contact, live) and the mobile app API. Previously the
                // public site fell back to config/site.php when this was NULL,
                // which made the schedule look hardcoded.
                $count = (int) $pdo->query('SELECT COUNT(*) FROM settings WHERE service_times IS NULL OR service_times = ""')->fetchColumn();
                if ($count > 0) {
                    $siteDefaults = require CONFIG_PATH . '/site.php';
                    $seed = $siteDefaults['service_times'] ?? '[]';
                    $pdo->prepare('UPDATE settings SET service_times = ? WHERE service_times IS NULL OR service_times = ""')->execute([$seed]);
                }
            },
            '2026_08_privacy_policy' => function (PDO $pdo): void {
                // Seed a comprehensive privacy policy page (served at /privacy-policy).
                // Content uses {{site_title}} / {{contact_email}} / {{contact_phone}}
                // / {{address}} tokens, resolved from the admin-editable settings at
                // render time so the page always reflects the site's current details.
                $check = $pdo->prepare('SELECT COUNT(*) FROM pages WHERE slug = ?');
                $check->execute(['privacy-policy']);
                if ((int) $check->fetchColumn() > 0) {
                    return;
                }
                $content = json_encode([
                    ['type' => 'text', 'heading' => 'Privacy Policy', 'body' => 'Effective date: {{effective_date}}' . "\n\n" . '{{site_title}} ("we", "us", or "our") is committed to protecting the privacy and personal information of everyone who visits our website, uses our mobile app, or interacts with our ministry. This Privacy Policy explains what information we collect, why we collect it, how we use it, and the choices you have. It applies to our website, our mobile application, and any related services we operate.', 'align' => 'center'],
                    ['type' => 'text', 'heading' => '1. Information We Collect', 'body' => "We collect information you give us directly, and information gathered automatically when you use our services.\n\nInformation you provide to us includes:\n- Contact details you submit through our contact and prayer request forms (such as your name and email address)\n- Newsletter sign-ups (email address)\n- Content you post publicly, such as prayer requests you choose to share\n- Any correspondence you send to us by email, phone, or through our website\n\nInformation collected automatically includes:\n- Device and usage information, such as your browser type, operating system, and pages you visit\n- Internet Protocol (IP) address and approximate location\n- Information collected through cookies and similar technologies\n- Likes, saves, and views of media content on our feed", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '2. How We Use Your Information', 'body' => "We use the information we collect to:\n- Operate and improve our website and mobile app, including our media feed, events, and sermons\n- Respond to your messages, prayer requests, and other enquiries\n- Send you the newsletters or updates you have asked to receive\n- Personalise your experience and show content that is relevant to you\n- Understand how our community engages with our content so we can serve better\n- Meet legal, regulatory, security, and administrative obligations", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '3. Legal Basis for Processing', 'body' => "Where data protection law applies to you, we rely on the following legal bases for processing your personal information:\n- Consent: where you have actively agreed, for example when you subscribe to our newsletter\n- Legitimate interest: to operate our ministry, respond to enquiries, and understand engagement with our content\n- Legal obligation: where we are required to process information to comply with the law", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '4. Sharing Your Information', 'body' => "We do not sell your personal information. We only share information in these limited circumstances:\n- With service providers who help us run our website, app, and communications (such as hosting, analytics, and email delivery providers)\n- When required by law, court order, or a lawful request from a public authority\n- In connection with safeguarding, where we believe it is necessary to protect the safety of any person\n- With your consent, or as otherwise described to you at the time", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '5. Cookies and Similar Technologies', 'body' => "Our website uses cookies and similar technologies to remember your preferences, understand how the site is used, and improve your experience. You can disable cookies through your browser settings, although some parts of the site may not work as well without them.\n\nThird-party services we use, such as embedded video players and analytics tools, may also set cookies subject to their own privacy policies.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '6. Data Security', 'body' => "We take reasonable technical and organisational measures to protect your personal information against loss, misuse, unauthorised access, alteration, and disclosure. No method of transmission over the internet or method of electronic storage is completely secure, so we cannot guarantee absolute security, but we work to protect your data to the best of our ability.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '7. Data Retention', 'body' => "We keep your personal information only for as long as is necessary for the purposes set out in this policy, or for as long as we are required to keep it by law. When information is no longer needed, we delete or anonymise it in a secure manner.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '8. Your Rights', 'body' => "Depending on where you live, you may have rights over your personal information, including the right to:\n- Access the information we hold about you\n- Correct inaccurate information\n- Request deletion of your information\n- Object to or restrict certain processing\n- Withdraw consent at any time\n\nTo exercise any of these rights, please contact us using the details below. We will respond within the time required by law and will not discriminate against you for exercising your rights.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '9. Children\u2019s Privacy', 'body' => "Our services are intended for a general audience and are not directed at children under the age of 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal information, please contact us and we will take steps to remove that information.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '10. Third-Party Links', 'body' => "Our website and app may contain links to third-party websites, such as video platforms and social media pages. We are not responsible for the privacy practices or content of those third parties, and we encourage you to review their privacy policies.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '11. Changes to This Policy', 'body' => "We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. When we make material changes, we will update the effective date at the top of this page and, where appropriate, notify you. Please review this page periodically to stay informed.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '12. Contact Us', 'body' => "If you have any questions about this Privacy Policy or how we handle your personal information, please contact us:\n\n{{site_title}}\n{{address}}\nEmail: {{contact_email}}\nPhone: {{contact_phone}}", 'align' => 'left'],
                ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
                $pdo->prepare('INSERT INTO pages (title, slug, eyebrow, content, meta_description, in_nav, nav_label, sort_order) VALUES (?, ?, ?, ?, ?, 1, ?, 90)')
                    ->execute([
                        'Privacy Policy',
                        'privacy-policy',
                        'Legal',
                        $content,
                        'How {{site_title}} collects, uses, and protects your personal information.',
                        'Privacy Policy',
                    ]);
            },
        ];
    }

    private static function addColumnIfMissing(PDO $pdo, string $table, string $column, string $definition, ?string $after): void
    {
        $check = $pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?');
        $check->execute([$table, $column]);
        if ((int) $check->fetchColumn() > 0) {
            return;
        }
        $sql = 'ALTER TABLE `' . $table . '` ADD COLUMN `' . $column . '` ' . $definition;
        if ($after) {
            $sql .= ' AFTER `' . $after . '`';
        }
        $pdo->exec($sql);
    }

    /** Builds a fresh PDO from arbitrary credentials without touching the singleton — used by the installer. */
    public static function testConnection(string $host, int $port, string $database, string $username, string $password): PDO
    {
        $dsn = sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4', $host, $port, $database);
        return new PDO($dsn, $username, $password, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true,
        ]);
    }

    /**
     * Naive but sufficient statement splitter for our own schema.sql. Splits on
     * ';' outside of string literals and backticks, so semicolons inside column
     * COMMENTS and seeded data can't break the import.
     */
    public static function importSqlFile(PDO $pdo, string $path): void
    {
        $sql = (string) file_get_contents($path);
        $sql = preg_replace('/^--.*$/m', '', $sql); // strip line comments
        foreach (self::splitStatements($sql) as $statement) {
            // query()+fetchAll() consumes any result set (e.g. an EXECUTE of a
            // SELECT) so the next statement never trips MySQL's "unbuffered
            // query active" (SQLSTATE 2014) error.
            $pdo->query($statement)->fetchAll();
        }
    }

    /** Splits SQL into statements, honouring '...' and `...` with '' / `` / \\ escapes. */
    private static function splitStatements(string $sql): array
    {
        $statements = [];
        $buffer = '';
        $length = strlen($sql);
        $quote = null;
        for ($i = 0; $i < $length; $i++) {
            $char = $sql[$i];
            if ($quote !== null) {
                $buffer .= $char;
                if ($char === $quote) {
                    // MySQL escapes a quote inside a string by doubling it ('' or ``).
                    if ($i + 1 < $length && $sql[$i + 1] === $quote) {
                        $buffer .= $sql[$i + 1];
                        $i++;
                    } else {
                        $quote = null;
                    }
                } elseif ($char === '\\' && $i + 1 < $length) {
                    $buffer .= $sql[$i + 1];
                    $i++;
                }
                continue;
            }
            if ($char === "'" || $char === '`') {
                $quote = $char;
                $buffer .= $char;
                continue;
            }
            if ($char === ';') {
                $trimmed = trim($buffer);
                if ($trimmed !== '') {
                    $statements[] = $trimmed;
                }
                $buffer = '';
                continue;
            }
            $buffer .= $char;
        }
        $trimmed = trim($buffer);
        if ($trimmed !== '') {
            $statements[] = $trimmed;
        }
        return $statements;
    }
}
