<?php
declare(strict_types=1);

/** Singleton PDO wrapper. Reads config/database.php (regenerated by the installer). */
class Database
{
    private static ?Database $instance = null;
    private PDO $connection;

    private function __construct()
    {
        $config = require CONFIG_PATH . '/database.php';
        $dsn = sprintf(
            '%s:host=%s;port=%d;dbname=%s;charset=%s',
            $config['driver'],
            $config['host'],
            $config['port'],
            $config['database'],
            $config['charset']
        );
        $this->connection = new PDO($dsn, $config['username'], $config['password'], [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);
    }

    public static function getInstance(): self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * True only when config/database.php exists with credentials that can actually
     * connect. Used at boot to detect a "new environment": a lock file copied from
     * another machine (or rotated credentials) must not make the app believe it is
     * installed and then crash with a raw PDOException on the first page load.
     */
    public static function isReachable(): bool
    {
        $configFile = CONFIG_PATH . '/database.php';
        if (!is_file($configFile)) {
            return false;
        }
        try {
            $config = require $configFile;
            if (empty($config['host']) || empty($config['database']) || empty($config['username'])) {
                return false;
            }
            $dsn = sprintf(
                '%s:host=%s;port=%d;dbname=%s;charset=%s',
                $config['driver'] ?? 'mysql',
                $config['host'],
                $config['port'] ?? 3306,
                $config['database'],
                $config['charset'] ?? 'utf8mb4'
            );
            $pdo = new PDO($dsn, $config['username'], $config['password'] ?? '', [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_TIMEOUT => 3,
            ]);
            $pdo->query('SELECT 1');
            return true;
        } catch (Throwable) {
            return false;
        }
    }

    public function getConnection(): PDO
    {
        return $this->connection;
    }

    /** Builds a fresh PDO from arbitrary credentials without touching the singleton — used by the installer. */
    public static function testConnection(string $host, int $port, string $database, string $username, string $password): PDO
    {
        $dsn = sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4', $host, $port, $database);
        return new PDO($dsn, $username, $password, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
    }

    /** Naive but sufficient statement splitter for our own schema.sql (no stored procs/triggers with embedded ';'). */
    public static function importSqlFile(PDO $pdo, string $path): void
    {
        $sql = (string) file_get_contents($path);
        $sql = preg_replace('/^--.*$/m', '', $sql); // strip line comments
        $statements = array_filter(array_map('trim', explode(';', $sql)));
        foreach ($statements as $statement) {
            $pdo->exec($statement);
        }
    }
}
