<?php
declare(strict_types=1);

/**
 * Generated by the installer on 2026-08-04 16:14:15.
 * Regenerate by deleting storage/installed.lock and re-running /install.
 */
return array (
  'driver' => 'mysql',
  'host' => '127.0.0.1',
  'port' => 3306,
  'database' => 'church_media',
  'username' => 'root',
  'password' => '',
  'charset' => 'utf8mb4',
);
